// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMNjWhAXxXs0KnhkYANcV2G2y-_bnXx-8',
    appId: '1:922636334084:web:e5a10d32965c4b3b1a7151',
    messagingSenderId: '922636334084',
    projectId: 'daftarbelanjaku-6c78f',
    authDomain: 'daftarbelanjaku-6c78f.firebaseapp.com',
    storageBucket: 'daftarbelanjaku-6c78f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAU75Y9bLtdrnkfJIhKZrHpwkIKy8k7X8g',
    appId: '1:922636334084:android:af45f16ddca66b761a7151',
    messagingSenderId: '922636334084',
    projectId: 'daftarbelanjaku-6c78f',
    storageBucket: 'daftarbelanjaku-6c78f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoRRvyApM65qk6h-BSPpBXTButjHlZlU4',
    appId: '1:922636334084:ios:27eb918b77c169071a7151',
    messagingSenderId: '922636334084',
    projectId: 'daftarbelanjaku-6c78f',
    storageBucket: 'daftarbelanjaku-6c78f.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoRRvyApM65qk6h-BSPpBXTButjHlZlU4',
    appId: '1:922636334084:ios:27eb918b77c169071a7151',
    messagingSenderId: '922636334084',
    projectId: 'daftarbelanjaku-6c78f',
    storageBucket: 'daftarbelanjaku-6c78f.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMNjWhAXxXs0KnhkYANcV2G2y-_bnXx-8',
    appId: '1:922636334084:web:697a560b1ec232c21a7151',
    messagingSenderId: '922636334084',
    projectId: 'daftarbelanjaku-6c78f',
    authDomain: 'daftarbelanjaku-6c78f.firebaseapp.com',
    storageBucket: 'daftarbelanjaku-6c78f.appspot.com',
  );
}
